param(
    [string]$EnvPath = ".env",
    [string]$DatabaseHost = "127.0.0.1",
    [int]$DatabasePort = 5432,
    [string]$DatabaseName = "product_monitor",
    [string]$DatabaseUser = "product_monitor",
    [string]$DatabasePassword = "",
    [string]$RedisUrl = "redis://127.0.0.1:6379/0",
    [switch]$InsecureCookies,
    [switch]$Force,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not [System.IO.Path]::IsPathRooted($EnvPath)) {
    $EnvPath = Join-Path $Root $EnvPath
}

function Fail([string]$Message) {
    Write-Host "[fail] $Message" -ForegroundColor Red
    exit 1
}

function Convert-SecureStringToPlainText([securestring]$Secret) {
    $Bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($Secret)
    try {
        return [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($Bstr)
    } finally {
        [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($Bstr)
    }
}

function Assert-StrongPassword([string]$Password) {
    if (-not $Password) {
        Fail "Database password is required"
    }
    if ($Password.Length -lt 16) {
        Fail "Database password must be at least 16 characters"
    }
    if ($Password -match "^(change-me|replace-with-strong-password|your-postgres-password)$") {
        Fail "Database password cannot be a placeholder"
    }
}

if ((Test-Path $EnvPath) -and -not $Force -and -not $DryRun) {
    Fail "env file already exists: $EnvPath; pass -Force to overwrite"
}

if (-not $DatabasePassword) {
    $Secret = Read-Host -Prompt "Database password" -AsSecureString
    $DatabasePassword = Convert-SecureStringToPlainText $Secret
}

Assert-StrongPassword $DatabasePassword

$EscapedUser = [System.Uri]::EscapeDataString($DatabaseUser)
$EscapedPassword = [System.Uri]::EscapeDataString($DatabasePassword)
$DatabaseUrl = "postgresql://${EscapedUser}:${EscapedPassword}@${DatabaseHost}:${DatabasePort}/${DatabaseName}"
$SessionCookieSecure = "true"
if ($InsecureCookies) {
    $SessionCookieSecure = "false"
}

$Content = @(
    "# Local production profile for the product monitor.",
    "# Generated by write-production-env.ps1.",
    "",
    "DATABASE_URL=$DatabaseUrl",
    "QUEUE_BACKEND=rq",
    "REDIS_URL=$RedisUrl",
    "START_BACKGROUND_WORKERS=false",
    "START_NOTIFICATION_WORKER=false",
    "SESSION_COOKIE_SECURE=$SessionCookieSecure",
    "CRAWLER_DOMAIN_DELAY_SECONDS=1.0"
)

Write-Host "Production env writer:" -ForegroundColor Cyan
Write-Host "  EnvPath=$EnvPath"
Write-Host "  Database=postgresql://${DatabaseUser}:<redacted>@${DatabaseHost}:${DatabasePort}/${DatabaseName}"
Write-Host "  RedisUrl=$RedisUrl"
Write-Host "  SESSION_COOKIE_SECURE=$SessionCookieSecure"

if ($DryRun) {
    Write-Host "Dry run only; no file written." -ForegroundColor Yellow
    exit 0
}

$Parent = Split-Path -Parent $EnvPath
if ($Parent -and -not (Test-Path $Parent)) {
    New-Item -ItemType Directory -Path $Parent | Out-Null
}

Set-Content -Path $EnvPath -Value $Content -Encoding ASCII
Write-Host "Wrote env file: $EnvPath" -ForegroundColor Green
